Pull Request review for the Authentication project in the Rails Module
jose-Abel/members-only pull request #1
Opened 2020-11-12 20:20 UTC by jose-Abel

Hello, 

We are requesting to have reviewed our implementation for the Authentication project in the Rails module that consists of building a clubhouse-like project where users can write posts and non-users cannot see the author's username of the posts.

Hoping to get amazing feedback, happy coding!

2020-11-12 22:04 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've an excellent job so far__.
- Nice README.MD file :+1: 
- Descriptive PR title and description :ok_hand: 
- Satisfactory commit messages :raised_hands: 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] **Do not commit files that are not related to the project. Instead, add them to the .gitignore file.**
- You committed your `node_modules` to your repo :thinking:  This is not a good practice.
- `node_modules` directory is a very large directory consisting of all the dependencies you used in your project. However, since you've added the dependencies to your Gemfile, you should include your `node_modules` to your `.gitignore` file.
- I could not test the functionality of your project because I couldn't clone the project (due to the large number of files in the node_modules directory that you committed).
- Follow [this article](https://gist.github.com/lmcneel/45594e550a3403d589bdcaad38138a83) on how to remove the `node_modules`.

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-11-13 04:07 UTC, voscarmv requested changes
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

Like the previous TSE, I also wasn't able to test this project. This time, the `bin` folder is missing. Without this folder, it's not possible to run the `rails db:create` command to begin testing.

Please make sure that you're able to clone a clean copy of your own repo into your machine, and do `bundle install` followed by `rails db:create`. before submitting again for review. This will guarantee that the next TSE will be able to actually download a fresh copy and test it on their side.

Please refer to this Stack Overflow thread for possible solutions to your problem. If all else fails, you can always contact me on Slack. I'm @ Oscar Mier there. I'll be sure to help you if you see it fit.

Here are some explanations of the problem you are experiencing:

https://stackoverflow.com/questions/38909344/why-does-the-rails-command-force-a-help-message-for-the-new-command
https://stackoverflow.com/questions/6400988/why-does-my-rails-command-always-create-a-new-application

### Submit these changes and request a new code review! 😄 👍

2020-11-13 12:18 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Please remove all logic from your views. There should be absolutely no logic in views. Instead, use helper methods to outsource view logic.
# \[OPTIONAL\] 

* [ ] A helper method to check if user is signed_in? can be handy here

```ruby
# must be a helper method to be used in views
helper_method :signed_in?
def signed_in?
  !current_user.nil?
end
```
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-11-13 19:23 UTC, rOluochKe approved these changes
Hello Team
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-13 19:34 UTC, merged